### ISSUE TITLE
[BUIlD] 프로젝트 기본 설정

### ISSUE THREAD

**Issue by hakilee** [capstone-urf/SoundUX-frontend#1]
## TODO
프로젝트의 기본 설정을 진행합니다. 

- [x] NextJS 프레임워크 추가 
- [x] Chakra-ui 스타일 적용
- [x] 기본 레이아웃 및 메인 페이지 추가
- [x] `axios` 의존성 추가
